### ISSUE TITLE
Code for FedFA

### ISSUE THREAD

**Issue by chenrxi** [tfzhou/FedFA#1]
I'm interested in your work. When can you open the source code? Thank you!

**Comment by tfzhou** [comment]
Hi @chenrxi , we have already released the code here. I am wondering whether you missed it for some reasons.

**Comment by chenrxi** [comment]
Could show the path to FedFAClient @tfzhou

**Comment by chenrxi** [comment]
it's true! I miss the fedfa layer in models

**Comment by chenrxi** [comment]
FedMixClient.py is missing! Could you provide more references? Thank you so much

**Comment by tfzhou** [comment]
Hi @chenrxi , We re-implement FedMix in another codebase, and have no plan to integrate it into this one. I suggest referring to original paper for official implementations.
